  // ===================== Styles =====================

  function injectStyles() {
    const css = document.createElement("style");
    css.textContent = [
      /* Toast */
      ".ai-edit-toast{position:fixed;top:20px;left:50%;transform:translateX(-50%) translateY(-20px);",
      "padding:10px 24px;border-radius:8px;font-size:14px;z-index:999999;opacity:0;transition:all .3s;",
      "pointer-events:none;font-family:-apple-system,BlinkMacSystemFont,sans-serif;box-shadow:0 4px 12px rgba(0,0,0,.15)}",
      ".ai-edit-toast.show{opacity:1;transform:translateX(-50%) translateY(0)}",
      ".ai-edit-toast-info{background:#1a73e8;color:#fff}",
      ".ai-edit-toast-success{background:#0d904f;color:#fff}",
      ".ai-edit-toast-error{background:#d93025;color:#fff}",
      ".ai-edit-toast-progress{background:#1a73e8;color:#fff;pointer-events:auto;cursor:default;",
      "display:flex;align-items:center;gap:10px}",
      ".ai-toast-spinner{width:14px;height:14px;border:2px solid rgba(255,255,255,.3);",
      "border-top-color:#fff;border-radius:50%;animation:ai-spin 0.8s linear infinite;flex-shrink:0}",
      "@keyframes ai-spin{to{transform:rotate(360deg)}}",
      ".ai-toast-stop{background:rgba(255,255,255,.2);border:1px solid rgba(255,255,255,.4);",
      "color:#fff;padding:2px 12px;border-radius:4px;font-size:12px;cursor:pointer;",
      "margin-left:6px;transition:background .15s}",
      ".ai-toast-stop:hover{background:rgba(255,255,255,.35)}",

      /* Context menu */
      ".ai-edit-menu{position:fixed;z-index:999998;min-width:240px;padding:4px 0;",
      "background:rgba(255,255,255,.96);backdrop-filter:blur(20px);",
      "border:1px solid rgba(0,0,0,.12);border-radius:8px;box-shadow:0 8px 30px rgba(0,0,0,.18);",
      "font-family:-apple-system,BlinkMacSystemFont,sans-serif;font-size:13px;color:#222;",
      "user-select:none;animation:ai-menu-in .12s ease-out}",
      "@keyframes ai-menu-in{from{opacity:0;transform:scale(.96)}to{opacity:1;transform:scale(1)}}",
      ".ai-menu-item{padding:6px 16px;cursor:pointer;display:flex;align-items:center;position:relative;white-space:nowrap}",
      ".ai-menu-item:hover{background:rgba(26,115,232,.1)}",
      ".ai-menu-icon{width:20px;text-align:center;margin-right:6px;font-size:12px}",
      ".ai-menu-arrow{margin-left:auto;font-size:10px;opacity:.5}",
      ".ai-menu-shortcut{margin-left:auto;font-size:11px;opacity:.4;padding-left:24px}",
      ".ai-menu-sep{height:1px;margin:4px 8px;background:rgba(0,0,0,.08)}",
      ".ai-menu-sub>.ai-menu-submenu{display:none;position:absolute;left:100%;top:-4px;",
      "min-width:200px;padding:4px 0;background:rgba(255,255,255,.96);backdrop-filter:blur(20px);",
      "border:1px solid rgba(0,0,0,.12);border-radius:8px;box-shadow:0 8px 30px rgba(0,0,0,.18)}",
      ".ai-menu-sub:hover>.ai-menu-submenu{display:block}",

      /* Dark theme */
      "@media(prefers-color-scheme:dark){",
      ".ai-edit-menu{background:rgba(40,40,40,.96);border-color:rgba(255,255,255,.12);color:#ddd}",
      ".ai-menu-item:hover{background:rgba(255,255,255,.1)}",
      ".ai-menu-sep{background:rgba(255,255,255,.1)}",
      ".ai-menu-sub>.ai-menu-submenu{background:rgba(40,40,40,.96);border-color:rgba(255,255,255,.12)}",
      "}",

      /* Settings overlay */
      ".ai-edit-overlay{position:fixed;top:0;left:0;width:100%;height:100%;",
      "background:rgba(0,0,0,.4);z-index:999997;display:flex;align-items:center;justify-content:center;",
      "animation:ai-fade-in .2s}",
      "@keyframes ai-fade-in{from{opacity:0}to{opacity:1}}",
      ".ai-edit-panel{background:#fff;border-radius:12px;width:560px;max-height:80vh;",
      "box-shadow:0 16px 48px rgba(0,0,0,.2);display:flex;flex-direction:column;",
      "font-family:-apple-system,BlinkMacSystemFont,sans-serif;overflow:hidden}",
      ".ai-edit-panel-header{display:flex;align-items:center;padding:16px 20px;border-bottom:1px solid #eee}",
      ".ai-edit-panel-header h3{margin:0;font-size:16px;font-weight:600}",
      ".ai-edit-close{margin-left:auto;background:none;border:none;font-size:22px;cursor:pointer;color:#999;padding:0 4px}",
      ".ai-edit-close:hover{color:#333}",
      ".ai-edit-panel-body{padding:20px;overflow-y:auto;flex:1}",
      ".ai-edit-panel-body h4{margin:16px 0 8px;font-size:14px;font-weight:600;color:#333}",
      ".ai-edit-panel-body h4:first-child{margin-top:0}",
      ".ai-edit-panel-body label{display:block;margin:8px 0 4px;font-size:12px;color:#666;font-weight:500}",
      ".ai-edit-panel-body textarea{width:100%;box-sizing:border-box;padding:8px 10px;",
      "border:1px solid #ddd;border-radius:6px;font-size:13px;font-family:SFMono-Regular,Menlo,monospace;",
      "resize:vertical;line-height:1.5;transition:border-color .2s}",
      ".ai-edit-panel-body textarea:focus{outline:none;border-color:#1a73e8}",
      ".ai-edit-hint{font-size:11px;color:#999;margin:4px 0 12px}",
      ".ai-edit-panel-footer{display:flex;align-items:center;padding:12px 20px;border-top:1px solid #eee;gap:8px}",
      ".ai-edit-spacer{flex:1}",
      ".ai-btn{padding:6px 16px;border-radius:6px;font-size:13px;cursor:pointer;border:none;font-weight:500;transition:background .15s}",
      ".ai-btn.primary{background:#1a73e8;color:#fff}.ai-btn.primary:hover{background:#1557b0}",
      ".ai-btn.secondary{background:#f1f3f4;color:#333}.ai-btn.secondary:hover{background:#e0e2e3}",

      /* Prompt dialog */
      ".ai-prompt-panel{background:#fff;border-radius:12px;width:480px;",
      "box-shadow:0 16px 48px rgba(0,0,0,.2);display:flex;flex-direction:column;",
      "font-family:-apple-system,BlinkMacSystemFont,sans-serif;overflow:hidden}",
      ".ai-prompt-body{padding:16px 20px}",
      ".ai-prompt-body label{display:block;font-size:13px;color:#555;margin-bottom:8px;font-weight:500}",
      ".ai-prompt-body textarea{width:100%;box-sizing:border-box;padding:10px 12px;",
      "border:1px solid #ddd;border-radius:8px;font-size:14px;font-family:-apple-system,BlinkMacSystemFont,sans-serif;",
      "resize:vertical;line-height:1.5;transition:border-color .2s}",
      ".ai-prompt-body textarea:focus{outline:none;border-color:#1a73e8}",
      ".ai-prompt-options{margin-top:10px;display:flex;align-items:center}",
      ".ai-prompt-checkbox{display:flex;align-items:center;font-size:13px;color:#555;cursor:pointer;gap:6px}",
      ".ai-prompt-checkbox input{margin:0;cursor:pointer}",

      /* Result dialog */
      ".ai-result-panel{width:560px}",
      ".ai-result-panel textarea{min-height:200px}",

      /* Provider select & text input */
      ".ai-select{width:100%;box-sizing:border-box;padding:6px 10px;border:1px solid #ddd;border-radius:6px;",
      "font-size:13px;font-family:-apple-system,BlinkMacSystemFont,sans-serif;background:#fff;",
      "cursor:pointer;transition:border-color .2s;outline:none;margin:4px 0}",
      ".ai-select:focus{border-color:#1a73e8}",
      ".ai-text-input{width:100%;box-sizing:border-box;padding:6px 10px;border:1px solid #ddd;border-radius:6px;",
      "font-size:13px;font-family:SFMono-Regular,Menlo,monospace;transition:border-color .2s;outline:none;margin:2px 0}",
      ".ai-text-input:focus{border-color:#1a73e8}",
      ".ai-provider-status{padding:4px 0}",
      ".ai-menu-item.disabled{opacity:.4;cursor:default;pointer-events:none}",

      /* Shortcut config */
      ".ai-shortcut-row{display:flex;align-items:center;gap:12px;margin:8px 0}",
      ".ai-shortcut-row label{flex:0 0 160px;font-size:13px;color:#555;font-weight:500;margin:0}",
      ".ai-shortcut-input{flex:1;padding:6px 12px;border:1px solid #ddd;border-radius:6px;",
      "font-size:14px;font-family:-apple-system,BlinkMacSystemFont,sans-serif;text-align:center;",
      "cursor:pointer;background:#f8f8f8;transition:border-color .2s,box-shadow .2s;outline:none}",
      ".ai-shortcut-input:focus{border-color:#1a73e8;box-shadow:0 0 0 2px rgba(26,115,232,.2);background:#fff}",

      /* Dark settings */
      "@media(prefers-color-scheme:dark){",
      ".ai-edit-panel{background:#2a2a2a;color:#ddd}",
      ".ai-edit-panel-header{border-color:#444}.ai-edit-panel-footer{border-color:#444}",
      ".ai-edit-panel-body h4{color:#ccc}",
      ".ai-edit-panel-body label{color:#999}",
      ".ai-edit-panel-body textarea{background:#333;border-color:#555;color:#ddd}",
      ".ai-edit-panel-body textarea:focus{border-color:#4a9eff}",
      ".ai-edit-close:hover{color:#eee}",
      ".ai-btn.secondary{background:#444;color:#ddd}.ai-btn.secondary:hover{background:#555}",
      ".ai-prompt-panel{background:#2a2a2a;color:#ddd}",
      ".ai-prompt-body label{color:#aaa}",
      ".ai-prompt-body textarea{background:#333;border-color:#555;color:#ddd}",
      ".ai-prompt-body textarea:focus{border-color:#4a9eff}",
      ".ai-prompt-checkbox{color:#aaa}",
      ".ai-shortcut-row label{color:#aaa}",
      ".ai-shortcut-input{background:#333;border-color:#555;color:#ddd}",
      ".ai-shortcut-input:focus{border-color:#4a9eff;box-shadow:0 0 0 2px rgba(74,158,255,.2);background:#3a3a3a}",
      ".ai-select{background:#333;border-color:#555;color:#ddd}",
      ".ai-select:focus{border-color:#4a9eff}",
      ".ai-text-input{background:#333;border-color:#555;color:#ddd}",
      ".ai-text-input:focus{border-color:#4a9eff}",
      "#ai-test-log{background:#1e1e1e !important;border-color:#555 !important;color:#ccc !important}",
      "}",

      /* Feishu progress overlay */
      ".ai-feishu-progress{position:fixed;top:0;left:0;width:100%;height:100%;",
      "background:rgba(0,0,0,.4);z-index:999997;display:flex;align-items:center;justify-content:center;",
      "opacity:0;transition:opacity .3s}",
      ".ai-feishu-progress.show{opacity:1}",
      ".ai-feishu-progress-inner{background:#fff;border-radius:16px;padding:32px 40px;",
      "min-width:360px;box-shadow:0 16px 48px rgba(0,0,0,.2);",
      "font-family:-apple-system,BlinkMacSystemFont,sans-serif;text-align:center}",
      ".ai-feishu-title{font-size:16px;font-weight:600;margin-bottom:24px;color:#333}",
      ".ai-feishu-steps{display:flex;flex-direction:column;gap:12px;text-align:left;margin-bottom:20px}",
      ".ai-feishu-step{display:flex;align-items:center;gap:10px;font-size:13px;color:#999;transition:color .3s}",
      ".ai-feishu-step.active{color:#1a73e8;font-weight:500}",
      ".ai-feishu-step.done{color:#0d904f}",
      ".ai-feishu-step-dot{width:18px;height:18px;border-radius:50%;border:2px solid #ddd;",
      "display:flex;align-items:center;justify-content:center;flex-shrink:0;transition:all .3s;font-size:10px}",
      ".ai-feishu-step.active .ai-feishu-step-dot{border-color:#1a73e8;",
      "animation:ai-spin 0.8s linear infinite;border-top-color:transparent}",
      ".ai-feishu-step.done .ai-feishu-step-dot{border-color:#0d904f;background:#0d904f;color:#fff}",
      ".ai-feishu-step.done .ai-feishu-step-dot::after{content:'✓'}",
      ".ai-feishu-status{font-size:12px;color:#888;margin-top:4px}",
      ".ai-feishu-stop{margin-top:16px;padding:6px 24px;border-radius:8px;font-size:13px;",
      "cursor:pointer;border:1px solid #e0e0e0;background:#fff;color:#d93025;font-weight:500;",
      "transition:all .15s;font-family:-apple-system,BlinkMacSystemFont,sans-serif}",
      ".ai-feishu-stop:hover{background:#fce8e6;border-color:#f5c6c2}",

      /* Feishu success overlay */
      ".ai-feishu-success{position:fixed;top:0;left:0;width:100%;height:100%;",
      "background:rgba(0,0,0,.4);z-index:999997;display:flex;align-items:center;justify-content:center;",
      "opacity:0;transition:opacity .3s}",
      ".ai-feishu-success.show{opacity:1}",
      ".ai-feishu-success-inner{background:#fff;border-radius:16px;padding:32px 40px;",
      "min-width:360px;box-shadow:0 16px 48px rgba(0,0,0,.2);",
      "font-family:-apple-system,BlinkMacSystemFont,sans-serif;text-align:center}",
      ".ai-feishu-success-icon{width:48px;height:48px;border-radius:50%;background:#0d904f;",
      "color:#fff;font-size:24px;display:flex;align-items:center;justify-content:center;margin:0 auto 16px}",
      ".ai-feishu-success-title{font-size:18px;font-weight:600;color:#333;margin-bottom:8px}",
      ".ai-feishu-success-doc{font-size:14px;color:#666;margin-bottom:16px}",
      ".ai-feishu-success-link{display:inline-block;color:#1a73e8;font-size:14px;font-weight:500;",
      "text-decoration:none;margin-bottom:20px}",
      ".ai-feishu-success-link:hover{text-decoration:underline}",
      ".ai-feishu-success-actions{display:flex;gap:8px;justify-content:center}",
      ".ai-feishu-btn-copy{padding:8px 20px;border-radius:8px;font-size:13px;cursor:pointer;",
      "border:1px solid #ddd;background:#f8f8f8;color:#333;font-weight:500;transition:background .15s}",
      ".ai-feishu-btn-copy:hover{background:#eee}",
      ".ai-feishu-btn-close{padding:8px 20px;border-radius:8px;font-size:13px;cursor:pointer;",
      "border:none;background:#1a73e8;color:#fff;font-weight:500;transition:background .15s}",
      ".ai-feishu-btn-close:hover{background:#1557b0}",

      /* Log panel */
      ".ai-log-panel{width:620px;max-height:85vh}",
      ".ai-log-body{padding:0 !important}",
      ".ai-log-list{font-family:SFMono-Regular,Menlo,Consolas,monospace;font-size:12px;",
      "line-height:1.6;max-height:60vh;overflow-y:auto;padding:12px 16px}",
      ".ai-log-entry{display:flex;align-items:flex-start;gap:8px;padding:3px 0;border-bottom:1px solid rgba(0,0,0,.04)}",
      ".ai-log-time{color:#999;flex-shrink:0;font-size:11px;min-width:56px}",
      ".ai-log-level{flex-shrink:0;font-size:10px;font-weight:600;min-width:42px;text-align:center;",
      "padding:1px 4px;border-radius:3px}",
      ".ai-log-info .ai-log-level{color:#1a73e8;background:rgba(26,115,232,.08)}",
      ".ai-log-warn .ai-log-level{color:#e37400;background:rgba(227,116,0,.08)}",
      ".ai-log-error .ai-log-level{color:#d93025;background:rgba(217,48,37,.08)}",
      ".ai-log-msg{flex:1;word-break:break-all;color:#333}",
      ".ai-log-empty{text-align:center;color:#999;padding:40px 20px;font-size:14px;",
      "font-family:-apple-system,BlinkMacSystemFont,sans-serif}",

      /* Feishu Doc Manager */
      ".ai-docmgr-panel{width:600px;max-height:80vh}",
      ".ai-docmgr-body{padding:0 !important}",
      ".ai-docmgr-empty{text-align:center;color:#999;padding:48px 20px;font-size:14px;",
      "font-family:-apple-system,BlinkMacSystemFont,sans-serif}",
      ".ai-docmgr-list{max-height:60vh;overflow-y:auto}",
      ".ai-docmgr-item{display:flex;align-items:center;padding:12px 20px;gap:12px;",
      "border-bottom:1px solid rgba(0,0,0,.06);transition:background .15s}",
      ".ai-docmgr-item:hover{background:rgba(0,0,0,.02)}",
      ".ai-docmgr-item:last-child{border-bottom:none}",
      ".ai-docmgr-item-main{flex:1;min-width:0}",
      ".ai-docmgr-item-title{font-size:14px;font-weight:500;margin-bottom:4px;",
      "white-space:nowrap;overflow:hidden;text-overflow:ellipsis}",
      ".ai-docmgr-link{color:#1a73e8;text-decoration:none;transition:color .15s}",
      ".ai-docmgr-link:hover{color:#1557b0;text-decoration:underline}",
      ".ai-docmgr-item-meta{display:flex;gap:12px;font-size:11px;color:#999}",
      ".ai-docmgr-time{flex-shrink:0}",
      ".ai-docmgr-local{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;",
      "max-width:240px;color:#bbb}",
      ".ai-docmgr-actions{display:flex;gap:6px;flex-shrink:0}",
      ".ai-docmgr-edit{padding:4px 12px;border-radius:6px;font-size:12px;",
      "cursor:pointer;border:1px solid #d2e3fc;background:#fff;color:#1a73e8;font-weight:500;",
      "transition:all .15s;white-space:nowrap}",
      ".ai-docmgr-edit:hover{background:#e8f0fe;border-color:#aecbfa}",
      ".ai-docmgr-edit:disabled{opacity:.5;cursor:default;pointer-events:none}",
      ".ai-docmgr-del{padding:4px 12px;border-radius:6px;font-size:12px;",
      "cursor:pointer;border:1px solid #e0e0e0;background:#fff;color:#d93025;font-weight:500;",
      "transition:all .15s;white-space:nowrap}",
      ".ai-docmgr-del:hover{background:#fce8e6;border-color:#f5c6c2}",
      ".ai-docmgr-del:disabled{opacity:.5;cursor:default;pointer-events:none}",
      ".ai-feishu-edit-bar{position:fixed;top:8px;right:12px;z-index:100000;",
      "display:flex;align-items:center;gap:8px;padding:6px 14px;border-radius:10px;",
      "background:linear-gradient(135deg,#1a73e8,#4a9eff);color:#fff;font-size:12px;",
      "font-family:-apple-system,BlinkMacSystemFont,sans-serif;box-shadow:0 4px 16px rgba(0,0,0,.18);",
      "opacity:0;transform:translateY(-8px);transition:all .3s ease;max-width:calc(100vw - 280px)}",
      ".ai-feishu-edit-bar.show{opacity:1;transform:translateY(0)}",
      ".ai-feishu-edit-bar-text{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:220px}",
      ".ai-feishu-edit-bar-actions{display:flex;gap:6px;flex-shrink:0}",
      ".ai-feishu-edit-bar-save{padding:3px 12px;border-radius:6px;font-size:11px;",
      "cursor:pointer;border:1px solid rgba(255,255,255,.4);background:rgba(255,255,255,.18);",
      "color:#fff;font-weight:600;transition:all .15s;white-space:nowrap}",
      ".ai-feishu-edit-bar-save:hover{background:rgba(255,255,255,.35)}",
      ".ai-feishu-edit-bar-close{width:22px;height:22px;border-radius:50%;font-size:13px;",
      "cursor:pointer;border:none;background:rgba(255,255,255,.18);color:#fff;line-height:1;",
      "display:flex;align-items:center;justify-content:center;transition:background .15s}",
      ".ai-feishu-edit-bar-close:hover{background:rgba(255,255,255,.35)}",
      ".ai-docmgr-search{padding:12px 20px 0;border-bottom:1px solid rgba(0,0,0,.06)}",
      ".ai-docmgr-search-input{width:100%;box-sizing:border-box;padding:8px 12px;",
      "border:1px solid #ddd;border-radius:8px;font-size:13px;outline:none;",
      "font-family:-apple-system,BlinkMacSystemFont,sans-serif;transition:border-color .2s;margin-bottom:12px}",
      ".ai-docmgr-search-input:focus{border-color:#1a73e8}",
      ".ai-docmgr-status{padding:8px 20px 4px;font-size:11px;color:#999}",
      ".ai-docmgr-status-row{display:flex;align-items:center;justify-content:space-between;gap:12px}",
      ".ai-docmgr-count{flex:1;min-width:0}",
      ".ai-docmgr-refresh{padding:4px 12px;border-radius:6px;font-size:12px;cursor:pointer;",
      "border:1px solid #d2e3fc;background:#fff;color:#1a73e8;font-weight:500;",
      "transition:all .15s;white-space:nowrap;flex-shrink:0;font-family:-apple-system,BlinkMacSystemFont,sans-serif}",
      ".ai-docmgr-refresh:hover:not(:disabled){background:#e8f0fe;border-color:#aecbfa}",
      ".ai-docmgr-refresh:disabled{opacity:.6;cursor:default}",
      ".ai-docmgr-badge{font-size:10px;padding:1px 6px;border-radius:4px;margin-left:8px;",
      "font-weight:500;vertical-align:middle}",
      ".ai-docmgr-badge-title{color:#1a73e8;background:rgba(26,115,232,.08)}",
      ".ai-docmgr-badge-content{color:#e37400;background:rgba(227,116,0,.08)}",
      ".ai-docmgr-pager{display:flex;align-items:center;justify-content:center;gap:12px;",
      "padding:12px 20px;border-top:1px solid rgba(0,0,0,.06)}",
      ".ai-docmgr-pager-btn{padding:5px 14px;border-radius:6px;font-size:12px;cursor:pointer;",
      "border:1px solid #ddd;background:#fff;color:#333;font-weight:500;transition:all .15s}",
      ".ai-docmgr-pager-btn:hover:not(:disabled){background:#f1f3f4}",
      ".ai-docmgr-pager-btn:disabled{opacity:.4;cursor:default}",
      ".ai-docmgr-pager-info{font-size:12px;color:#999}",

      /* Dark Feishu */
      "@media(prefers-color-scheme:dark){",
      ".ai-feishu-progress-inner{background:#2a2a2a;color:#ddd}",
      ".ai-feishu-title{color:#eee}",
      ".ai-feishu-step-dot{border-color:#555}",
      ".ai-feishu-status{color:#888}",
      ".ai-feishu-stop{background:#3a3a3a;border-color:#555;color:#f28b82}",
      ".ai-feishu-stop:hover{background:#4a2a2a;border-color:#f28b82}",
      ".ai-feishu-success-inner{background:#2a2a2a;color:#ddd}",
      ".ai-feishu-success-title{color:#eee}",
      ".ai-feishu-success-doc{color:#aaa}",
      ".ai-feishu-success-link{color:#4a9eff}",
      ".ai-feishu-btn-copy{background:#444;border-color:#555;color:#ddd}",
      ".ai-feishu-btn-copy:hover{background:#555}",
      ".ai-log-entry{border-color:rgba(255,255,255,.06)}",
      ".ai-log-msg{color:#ccc}",
      ".ai-log-empty{color:#777}",
      ".ai-docmgr-item{border-color:rgba(255,255,255,.08)}",
      ".ai-docmgr-item:hover{background:rgba(255,255,255,.04)}",
      ".ai-docmgr-link{color:#4a9eff}",
      ".ai-docmgr-link:hover{color:#7ab8ff}",
      ".ai-docmgr-local{color:#666}",
      ".ai-docmgr-empty{color:#777}",
      ".ai-docmgr-edit{background:#3a3a3a;border-color:#555;color:#8ab4f8}",
      ".ai-docmgr-edit:hover{background:#444;border-color:#666}",
      ".ai-docmgr-del{background:#3a3a3a;border-color:#555;color:#f28b82}",
      ".ai-docmgr-del:hover{background:#4a2a2a;border-color:#f28b82}",
      ".ai-docmgr-refresh{background:#3a3a3a;border-color:#555;color:#8ab4f8}",
      ".ai-docmgr-refresh:hover:not(:disabled){background:#444;border-color:#666}",
      ".ai-docmgr-search{border-color:rgba(255,255,255,.08)}",
      ".ai-docmgr-search-input{background:#333;border-color:#555;color:#ddd}",
      ".ai-docmgr-search-input:focus{border-color:#4a9eff}",
      ".ai-docmgr-pager{border-color:rgba(255,255,255,.08)}",
      ".ai-docmgr-pager-btn{background:#3a3a3a;border-color:#555;color:#ddd}",
      ".ai-docmgr-pager-btn:hover:not(:disabled){background:#444}",
      "}",
    ].join("\n");
    document.head.appendChild(css);
  }
