  // ===================== Styles =====================

  function injectStyles() {
    const css = document.createElement("style");
    css.textContent = [
      /* Toast */
      ".ai-edit-toast{position:fixed;top:20px;left:50%;transform:translateX(-50%) translateY(-20px);",
      "padding:10px 24px;border-radius:8px;font-size:14px;z-index:999999;opacity:0;transition:all .3s;",
      "pointer-events:none;font-family:-apple-system,BlinkMacSystemFont,sans-serif;box-shadow:0 4px 12px rgba(0,0,0,.15)}",
      ".ai-edit-toast.show{opacity:1;transform:translateX(-50%) translateY(0)}",
      ".ai-edit-toast-info{background:#1a73e8;color:#fff}",
      ".ai-edit-toast-success{background:#0d904f;color:#fff}",
      ".ai-edit-toast-error{background:#d93025;color:#fff}",
      ".ai-edit-toast-progress{background:#1a73e8;color:#fff;pointer-events:auto;cursor:default;",
      "display:flex;align-items:center;gap:10px}",
      ".ai-toast-spinner{width:14px;height:14px;border:2px solid rgba(255,255,255,.3);",
      "border-top-color:#fff;border-radius:50%;animation:ai-spin 0.8s linear infinite;flex-shrink:0}",
      "@keyframes ai-spin{to{transform:rotate(360deg)}}",
      ".ai-toast-stop{background:rgba(255,255,255,.2);border:1px solid rgba(255,255,255,.4);",
      "color:#fff;padding:2px 12px;border-radius:4px;font-size:12px;cursor:pointer;",
      "margin-left:6px;transition:background .15s}",
      ".ai-toast-stop:hover{background:rgba(255,255,255,.35)}",

      /* Context menu */
      ".ai-edit-menu{position:fixed;z-index:999998;min-width:240px;padding:4px 0;",
      "background:rgba(255,255,255,.96);backdrop-filter:blur(20px);",
      "border:1px solid rgba(0,0,0,.12);border-radius:8px;box-shadow:0 8px 30px rgba(0,0,0,.18);",
      "font-family:-apple-system,BlinkMacSystemFont,sans-serif;font-size:13px;color:#222;",
      "user-select:none;animation:ai-menu-in .12s ease-out}",
      "@keyframes ai-menu-in{from{opacity:0;transform:scale(.96)}to{opacity:1;transform:scale(1)}}",
      ".ai-menu-item{padding:6px 16px;cursor:pointer;display:flex;align-items:center;position:relative;white-space:nowrap}",
      ".ai-menu-item:hover{background:rgba(26,115,232,.1)}",
      ".ai-menu-icon{width:20px;text-align:center;margin-right:6px;font-size:12px}",
      ".ai-menu-arrow{margin-left:auto;font-size:10px;opacity:.5}",
      ".ai-menu-shortcut{margin-left:auto;font-size:11px;opacity:.4;padding-left:24px}",
      ".ai-menu-sep{height:1px;margin:4px 8px;background:rgba(0,0,0,.08)}",
      ".ai-menu-sub>.ai-menu-submenu{display:none;position:absolute;left:100%;top:-4px;",
      "min-width:200px;padding:4px 0;background:rgba(255,255,255,.96);backdrop-filter:blur(20px);",
      "border:1px solid rgba(0,0,0,.12);border-radius:8px;box-shadow:0 8px 30px rgba(0,0,0,.18)}",
      ".ai-menu-sub:hover>.ai-menu-submenu{display:block}",

      /* Dark theme */
      "@media(prefers-color-scheme:dark){",
      ".ai-edit-menu{background:rgba(40,40,40,.96);border-color:rgba(255,255,255,.12);color:#ddd}",
      ".ai-menu-item:hover{background:rgba(255,255,255,.1)}",
      ".ai-menu-sep{background:rgba(255,255,255,.1)}",
      ".ai-menu-sub>.ai-menu-submenu{background:rgba(40,40,40,.96);border-color:rgba(255,255,255,.12)}",
      "}",

      /* Settings overlay */
      ".ai-edit-overlay{position:fixed;top:0;left:0;width:100%;height:100%;",
      "background:rgba(0,0,0,.4);z-index:999997;display:flex;align-items:center;justify-content:center;",
      "animation:ai-fade-in .2s}",
      "@keyframes ai-fade-in{from{opacity:0}to{opacity:1}}",
      ".ai-edit-panel{background:#fff;border-radius:12px;width:560px;max-height:80vh;",
      "box-shadow:0 16px 48px rgba(0,0,0,.2);display:flex;flex-direction:column;",
      "font-family:-apple-system,BlinkMacSystemFont,sans-serif;overflow:hidden}",
      ".ai-edit-panel-header{display:flex;align-items:center;padding:16px 20px;border-bottom:1px solid #eee}",
      ".ai-edit-panel-header h3{margin:0;font-size:16px;font-weight:600}",
      ".ai-edit-close{margin-left:auto;background:none;border:none;font-size:22px;cursor:pointer;color:#999;padding:0 4px}",
      ".ai-edit-close:hover{color:#333}",
      ".ai-edit-panel-body{padding:20px;overflow-y:auto;flex:1}",
      ".ai-edit-panel-body h4{margin:16px 0 8px;font-size:14px;font-weight:600;color:#333}",
      ".ai-edit-panel-body h4:first-child{margin-top:0}",
      ".ai-edit-panel-body label{display:block;margin:8px 0 4px;font-size:12px;color:#666;font-weight:500}",
      ".ai-edit-panel-body textarea{width:100%;box-sizing:border-box;padding:8px 10px;",
      "border:1px solid #ddd;border-radius:6px;font-size:13px;font-family:SFMono-Regular,Menlo,monospace;",
      "resize:vertical;line-height:1.5;transition:border-color .2s}",
      ".ai-edit-panel-body textarea:focus{outline:none;border-color:#1a73e8}",
      ".ai-edit-hint{font-size:11px;color:#999;margin:4px 0 12px}",
      ".ai-edit-panel-footer{display:flex;align-items:center;padding:12px 20px;border-top:1px solid #eee;gap:8px}",
      ".ai-edit-spacer{flex:1}",
      ".ai-btn{padding:6px 16px;border-radius:6px;font-size:13px;cursor:pointer;border:none;font-weight:500;transition:background .15s}",
      ".ai-btn.primary{background:#1a73e8;color:#fff}.ai-btn.primary:hover{background:#1557b0}",
      ".ai-btn.secondary{background:#f1f3f4;color:#333}.ai-btn.secondary:hover{background:#e0e2e3}",

      /* Prompt dialog */
      ".ai-prompt-panel{background:#fff;border-radius:12px;width:480px;",
      "box-shadow:0 16px 48px rgba(0,0,0,.2);display:flex;flex-direction:column;",
      "font-family:-apple-system,BlinkMacSystemFont,sans-serif;overflow:hidden}",
      ".ai-prompt-body{padding:16px 20px}",
      ".ai-prompt-body label{display:block;font-size:13px;color:#555;margin-bottom:8px;font-weight:500}",
      ".ai-prompt-body textarea{width:100%;box-sizing:border-box;padding:10px 12px;",
      "border:1px solid #ddd;border-radius:8px;font-size:14px;font-family:-apple-system,BlinkMacSystemFont,sans-serif;",
      "resize:vertical;line-height:1.5;transition:border-color .2s}",
      ".ai-prompt-body textarea:focus{outline:none;border-color:#1a73e8}",
      ".ai-prompt-options{margin-top:10px;display:flex;align-items:center}",
      ".ai-prompt-checkbox{display:flex;align-items:center;font-size:13px;color:#555;cursor:pointer;gap:6px}",
      ".ai-prompt-checkbox input{margin:0;cursor:pointer}",

      /* Result dialog */
      ".ai-result-panel{width:560px}",
      ".ai-result-panel textarea{min-height:200px}",

      /* Provider select & text input */
      ".ai-select{width:100%;box-sizing:border-box;padding:6px 10px;border:1px solid #ddd;border-radius:6px;",
      "font-size:13px;font-family:-apple-system,BlinkMacSystemFont,sans-serif;background:#fff;",
      "cursor:pointer;transition:border-color .2s;outline:none;margin:4px 0}",
      ".ai-select:focus{border-color:#1a73e8}",
      ".ai-text-input{width:100%;box-sizing:border-box;padding:6px 10px;border:1px solid #ddd;border-radius:6px;",
      "font-size:13px;font-family:SFMono-Regular,Menlo,monospace;transition:border-color .2s;outline:none;margin:2px 0}",
      ".ai-text-input:focus{border-color:#1a73e8}",
      ".ai-provider-status{padding:4px 0}",
      ".ai-menu-item.disabled{opacity:.4;cursor:default;pointer-events:none}",

      /* Shortcut config */
      ".ai-shortcut-row{display:flex;align-items:center;gap:12px;margin:8px 0}",
      ".ai-shortcut-row label{flex:0 0 160px;font-size:13px;color:#555;font-weight:500;margin:0}",
      ".ai-shortcut-input{flex:1;padding:6px 12px;border:1px solid #ddd;border-radius:6px;",
      "font-size:14px;font-family:-apple-system,BlinkMacSystemFont,sans-serif;text-align:center;",
      "cursor:pointer;background:#f8f8f8;transition:border-color .2s,box-shadow .2s;outline:none}",
      ".ai-shortcut-input:focus{border-color:#1a73e8;box-shadow:0 0 0 2px rgba(26,115,232,.2);background:#fff}",

      /* Dark settings */
      "@media(prefers-color-scheme:dark){",
      ".ai-edit-panel{background:#2a2a2a;color:#ddd}",
      ".ai-edit-panel-header{border-color:#444}.ai-edit-panel-footer{border-color:#444}",
      ".ai-edit-panel-body h4{color:#ccc}",
      ".ai-edit-panel-body label{color:#999}",
      ".ai-edit-panel-body textarea{background:#333;border-color:#555;color:#ddd}",
      ".ai-edit-panel-body textarea:focus{border-color:#4a9eff}",
      ".ai-edit-close:hover{color:#eee}",
      ".ai-btn.secondary{background:#444;color:#ddd}.ai-btn.secondary:hover{background:#555}",
      ".ai-prompt-panel{background:#2a2a2a;color:#ddd}",
      ".ai-prompt-body label{color:#aaa}",
      ".ai-prompt-body textarea{background:#333;border-color:#555;color:#ddd}",
      ".ai-prompt-body textarea:focus{border-color:#4a9eff}",
      ".ai-prompt-checkbox{color:#aaa}",
      ".ai-shortcut-row label{color:#aaa}",
      ".ai-shortcut-input{background:#333;border-color:#555;color:#ddd}",
      ".ai-shortcut-input:focus{border-color:#4a9eff;box-shadow:0 0 0 2px rgba(74,158,255,.2);background:#3a3a3a}",
      ".ai-select{background:#333;border-color:#555;color:#ddd}",
      ".ai-select:focus{border-color:#4a9eff}",
      ".ai-text-input{background:#333;border-color:#555;color:#ddd}",
      ".ai-text-input:focus{border-color:#4a9eff}",
      "#ai-test-log{background:#1e1e1e !important;border-color:#555 !important;color:#ccc !important}",
      "}",
    ].join("\n");
    document.head.appendChild(css);
  }
